// Generated by CoffeeScript 1.4.0

exports.setHeaders = function(res) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header({
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
  });
  return res.header('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type');
};
